import piso13Banner from "../../assets/2b57e070-b971-4b19-9b62-2a308b32a46e.jpg";
import piso13Screen1 from "../../assets/9042c8d8-6c09-4a40-94b4-8f578d41993b.jpg";
import piso13Screen2 from "../../assets/cfc0baab-9c81-4a1c-beb5-f19c84a6099c.jpg";
import piso13Screen3 from "../../assets/47c63198-3d01-4a16-9178-21f8cfffdf3d.jpg";
import piso13Screen4 from "../../assets/7a0f8849-d5a7-4cf1-8483-e91eca54ace7.jpg";
import piso13Screen5 from "../../assets/af9aacad-76f4-436f-8015-7e2d641a7dee.jpg";
import piso13Collage from "../../assets/15d5c8be-dece-4365-accf-bc19d396df54.jpg";
import piso13Screen6 from "../../assets/e8677949-6cfc-4487-8a53-341ee7965017.jpg";
import piso13Screen7 from "../../assets/53c8189e-3203-430b-90b6-d0741c659885.jpg";

export const games = [
  {
    id: 1,
    title: "Viruta en el Piso 13",
    developer: "Priruta Studios",
    publisher: "Priruta",
    releaseDate: "Próximamente 2026",
    price: 14.99,
    discount: 0,
    featured: true,
    banner: piso13Banner,
    thumbnail: piso13Screen1,
    screenshots: [piso13Screen1, piso13Screen2, piso13Screen3, piso13Screen4, piso13Screen5, piso13Screen6, piso13Screen7],
    tags: ["Acción", "Horror", "Pixel Art", "Side-Scroller", "Indie"],
    rating: 95,
    reviews: "Muy Positivas",
    reviewCount: 2847,
    description:
      "El piso que no existe, el terror que nunca termina. Eres Viruta, un técnico de mantenimiento que descubre el piso 13 de la corporación Apex — un lugar que no aparece en ningún plano. Enfréntate a monstruos de cable, ratas mutantes y la temible Brenda de RH en este side-scroller de acción y horror pixel art.",
    features: [
      "13 niveles de terror corporativo",
      "5 jefes épicos incluyendo la Gerente de RH",
      "Sistema de combate con martillo y power-ups",
      "Pixel art detallado con animaciones fluidas",
      "Banda sonora chiptune atmospheric horror",
      "Secretos ocultos en cada nivel",
    ],
    requirements: {
      os: "Windows 10 / macOS 12+",
      processor: "Intel i3 / Apple M1",
      memory: "4 GB RAM",
      graphics: "Integrada",
      storage: "500 MB",
    },
  },
  {
    id: 2,
    title: "Dead Pixel Protocol",
    developer: "NeonByte Games",
    publisher: "NeonByte",
    releaseDate: "15 Ene 2026",
    price: 19.99,
    discount: 25,
    featured: true,
    banner: piso13Collage,
    thumbnail: piso13Screen5,
    screenshots: [piso13Screen5, piso13Screen6, piso13Screen7],
    tags: ["Horror", "Survival", "Pixel Art", "Co-op"],
    rating: 88,
    reviews: "Muy Positivas",
    reviewCount: 1203,
    description:
      "Un virus ha corrompido la red. Navega por servidores infectados, evita firewalls letales y restaura el protocolo antes de que el sistema colapse. Survival horror cooperativo en pixel art donde cada paquete de datos cuenta.",
    features: [
      "Co-op online para 2-4 jugadores",
      "Generación procedural de niveles",
      "Crafting de herramientas digitales",
      "6 clases de personaje únicas",
    ],
    requirements: {
      os: "Windows 10 / macOS 12+",
      processor: "Intel i5 / Apple M1",
      memory: "8 GB RAM",
      graphics: "GTX 1050 / Integrada Apple",
      storage: "1 GB",
    },
  },
  {
    id: 3,
    title: "Neon Mantis",
    developer: "CyberForge",
    publisher: "CyberForge Interactive",
    releaseDate: "8 Mar 2026",
    price: 12.99,
    discount: 40,
    featured: false,
    banner: piso13Screen2,
    thumbnail: piso13Screen4,
    screenshots: [piso13Screen4, piso13Screen3, piso13Screen1],
    tags: ["Acción", "Cyberpunk", "Metroidvania", "Indie"],
    rating: 92,
    reviews: "Extremadamente Positivas",
    reviewCount: 5621,
    description:
      "En las profundidades de Neo-Kyoto, una mantis cibernética despierta. Explora un mundo interconectado, desbloquea habilidades biomecánicas y descubre la verdad detrás del Proyecto Mantis en este metroidvania cyberpunk.",
    features: [
      "Mapa interconectado estilo Metroidvania",
      "12 habilidades biomecánicas",
      "New Game+ con enemigos remezclados",
      "Múltiples finales",
    ],
    requirements: {
      os: "Windows 10 / macOS 11+",
      processor: "Intel i3 / Apple M1",
      memory: "4 GB RAM",
      graphics: "Integrada",
      storage: "800 MB",
    },
  },
  {
    id: 4,
    title: "Firewall Breach",
    developer: "Priruta Studios",
    publisher: "Priruta",
    releaseDate: "22 Feb 2026",
    price: 9.99,
    discount: 0,
    featured: false,
    banner: piso13Screen7,
    thumbnail: piso13Screen7,
    screenshots: [piso13Screen7, piso13Screen6, piso13Screen2],
    tags: ["Puzzle", "Hacker", "Indie", "Pixel Art"],
    rating: 79,
    reviews: "Positivas",
    reviewCount: 892,
    description:
      "Hackea tu camino a través de 100 niveles de puzzles lógicos. Cada firewall es un rompecabezas único. Conecta nodos, evita trampas ICE y demuestra que eres el mejor hacker del submundo digital.",
    features: [
      "100 puzzles de dificultad creciente",
      "Editor de niveles incluido",
      "Tabla de clasificación global",
      "Modo speedrun con timer integrado",
    ],
    requirements: {
      os: "Windows 7+ / macOS 10.15+",
      processor: "Cualquiera",
      memory: "2 GB RAM",
      graphics: "Integrada",
      storage: "200 MB",
    },
  },
  {
    id: 5,
    title: "Rata Eléctrica",
    developer: "VoltByte Studio",
    publisher: "VoltByte",
    releaseDate: "Próximamente 2026",
    price: 7.99,
    discount: 15,
    featured: false,
    banner: piso13Screen6,
    thumbnail: piso13Screen6,
    screenshots: [piso13Screen6, piso13Screen1, piso13Screen5],
    tags: ["Acción", "Roguelike", "Pixel Art", "Indie"],
    rating: 84,
    reviews: "Muy Positivas",
    reviewCount: 3104,
    description:
      "Eres una rata mutante con poderes eléctricos atrapada en los ductos de una megacorporación. Cada carrera es diferente en este roguelike de acción frenética con upgrades permanentes y jefes aleatorios.",
    features: [
      "Roguelike con runs de 30 minutos",
      "50+ upgrades combinables",
      "8 jefes con variantes aleatorias",
      "Desbloquea 4 ratas jugables",
    ],
    requirements: {
      os: "Windows 10 / macOS 11+",
      processor: "Intel i3 / Apple M1",
      memory: "4 GB RAM",
      graphics: "Integrada",
      storage: "400 MB",
    },
  },
  {
    id: 6,
    title: "Servidor Muerto",
    developer: "GlitchLab",
    publisher: "GlitchLab",
    releaseDate: "10 Abr 2026",
    price: 24.99,
    discount: 0,
    featured: false,
    banner: piso13Screen3,
    thumbnail: piso13Screen3,
    screenshots: [piso13Screen3, piso13Screen4, piso13Screen5],
    tags: ["Horror", "Survival", "Simulación", "Pixel Art"],
    rating: 91,
    reviews: "Extremadamente Positivas",
    reviewCount: 1567,
    description:
      "Administra un data center embrujado. De día, repara servidores y atiende tickets. De noche, sobrevive a las entidades digitales que emergen de los racks corruptos. ¿Cuántos turnos aguantarás?",
    features: [
      "Ciclo día/noche con mecánicas únicas",
      "Sistema de gestión de servidores",
      "Terror psicológico progresivo",
      "Múltiples finales según tus decisiones",
    ],
    requirements: {
      os: "Windows 10 / macOS 12+",
      processor: "Intel i5 / Apple M1",
      memory: "8 GB RAM",
      graphics: "GTX 960 / Apple M1",
      storage: "1.5 GB",
    },
  },
];
